install:
	./gradlew clean install

run-dist:
	./build/install/collections/bin/collections

build:
	./gradlew clean build

check:
	gradle checkstyleMain

clean:
	./gradlew clean

run:
	./gradlew run

installDist:
	./gradlew installDist

test:
	gradle test
